version: "3.5"

services:
  front-end:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: npm start
    volumes:
      - .:/usr/app
    hostname: localhost
    ports:
      - 3000:3000
