AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ElasticContainerRepo:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: IMMUTABLE
      RepositoryName: fitness-client-repo


Outputs:
  ElasticContainerRepo:
    Description: Created ECR name is 
    Value: !Ref ElasticContainerRepo
    

